#+TITLE: Hello Again
#+AUTHOR: PerlStalker
#+DATE: [2010-09-27 Mon 11:46]
#+begin_html
---
layout: post
title: Hello Again
date: 2010-09-27 11:46
comments: true
categories: [meta]
---
#+end_html
/Originally posted at [2010-09-27 Mon 11:46]/

Welcome to my new, improved and slightly zombie-like SysAdmin site. This site
had been a general place to drop my docs on various things I do as a systems
administrator. At first, I thought I would put this up at my main blog, 
[[http://perlstalker.blogspot.com/][PerlStalker's Ramblings]], but that site went all politics all the time. So, I'm
moving the old posts out of tikiwiki and blogger and putting them here.

Most of the docs here, so far, are from my days at [[http://www.amigo.net/][amigo.net]] with a few things
from a virtualization trade study at [[http://www.adams.edu/][Adams State College]] a couple of years
ago. More stuff will be coming but at a much slower rate than Ramblings. The
posts will be mostly notes and may even be organized.

The site itself is still evolving. I have comments turned off until I decide
what I want to do with them. It's the same with the search engine. We'll see
where it goes.
